import { GetCompanySubscription } from "../../../application/usecase/companyUsecase/getCompanySubscription.usecase";
import { GetSubscriptionPlans } from "../../../application/usecase/subscriptionUseCase/getSubscription.usecase";
import { IsPlanAvailableUseCase } from "../../../application/usecase/subscriptionUseCase/isPlanAvailable.usecase";
import { PlanPolicy } from "../../../application/usecase/subscriptionUseCase/planpolicy.usecase";
import { SubscriptionUsecase } from "../../../application/usecase/subscriptionUseCase/subscription.usecase";
import { ICompanyRepository } from "../../../domain/repositories/company.repo";
import { IProjectRepository } from "../../../domain/repositories/project.repo";
import { ISubscription } from "../../../domain/repositories/subscription.repo";
import { ITeamRepository } from "../../../domain/repositories/team.repo";
import { IUserRepository } from "../../../domain/repositories/user.repo";
import { IWorkspaceRepository } from "../../../domain/repositories/workspace.repo";
import { CompanyRepositoryImp } from "../../../infrastructure/repositories/repoImplementations/company.repositoryImp";
import { projectRepositoryImp } from "../../../infrastructure/repositories/repoImplementations/project.repositoryImp";
import { SubscriptionImp } from "../../../infrastructure/repositories/repoImplementations/subscriptoin.repositoryImp";
import { TeamRepositoryImp } from "../../../infrastructure/repositories/repoImplementations/team.repositoryImp";
import { userRepositoryImp } from "../../../infrastructure/repositories/repoImplementations/user.repositoryImp";
import { WorkspaceRepoImp } from "../../../infrastructure/repositories/repoImplementations/workspace.repositoryImp";

const userRepo: IUserRepository = new userRepositoryImp();
const teamRepo: ITeamRepository = new TeamRepositoryImp();
const companyRepository: ICompanyRepository = new CompanyRepositoryImp();
const subscriptionRepository: ISubscription = new SubscriptionImp();
const workspaceRepo: IWorkspaceRepository = new WorkspaceRepoImp();
const projectRepo: IProjectRepository = new projectRepositoryImp(userRepo);

export const subscribe = new SubscriptionUsecase(companyRepository, subscriptionRepository);
export const getSubscription = new GetSubscriptionPlans(subscriptionRepository);
export const planPolicyUsecase = new PlanPolicy(teamRepo, companyRepository, workspaceRepo, projectRepo);
export const companySubscription = new GetCompanySubscription(companyRepository);
export const isPlanAvailable = new IsPlanAvailableUseCase(subscriptionRepository);