
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon --watch src --ext ts --exec ts-node src/server.ts
    environment:
      - MONGO_URI=mongodb://mongo:27017/projexpert
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
volumes:
  mongo_data:   
